version: '3.8'

services:
  # MySQL 数据库
  db:
    image: mysql:8.0
    container_name: itwords-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_DATABASE: mysql_itwordslearning
    volumes:
      - mysql_data:/var/lib/mysql
      - ./deployment-scripts/database-setup.sql:/docker-entrypoint-initdb.d/init.sql
    # ports:
    #   - "3306:3306"  # 不暴露到主机，只在容器内部使用
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - app-network

  # Spring Boot 后端
  backend:
    build:
      context: ./itwordslearning_api
      dockerfile: Dockerfile
    container_name: itwords-backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:mysql://db:3306/mysql_itwordslearning?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - CORS_ORIGINS=http://localhost:3000,http://frontend:80
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  # Vue.js 前端
  frontend:
    build:
      context: ./IT-wordslearing_display3.0 2
      dockerfile: Dockerfile
    container_name: itwords-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge 